### ISSUE TITLE
Add new tag when bumping version

### ISSUE THREAD

**Issue by linsui** [slartus/4pdaClient-plus#96]
Could you please add a new tag when bumping the version? So that F-Droid auto update can work. Thanks!

**Comment by slartus** [comment]
done

**Comment by linsui** [comment]
Thanks!

**Comment by ildar** [comment]
It's done wrong unfortunately, because in 3.5.8.9 tag's tree
updateinfo.json unchanged (version/versionCode is wrong).
I guess the tag should be moved a few commits later where versionCode is
fixed.
As the result F-Droid again doesn't have the recent version.

Or we can wait if the newer release is near.

**Comment by linsui** [comment]
We can add a new version manully.

**Comment by licaon-kter** [comment]
Removed checks for now since they fail: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10431

**Comment by ildar** [comment]
Why? if the upsteam will tag the next release correctly, it should work.
And I hope they will.
